name: Python CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.8.11'

      - name: Install dependencies
        run: uv sync --dev --all-extras --frozen

      - name: Check formatting (ruff)
        run: uv run ruff format --check .

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Run tests
        run: uv run make run_tests

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          format: cobertura
          file: coverage.xml